# Generated by Django 3.1.6 on 2021-02-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='review_by_patient',
        ),
    ]
