# Generated by Django 3.1.6 on 2021-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_remove_donor_review_by_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='voter_id',
            field=models.CharField(default='blank', max_length=200, unique=True),
        ),
    ]
