# Generated by Django 3.1.6 on 2021-02-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20210215_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
