# Generated by Django 3.1.6 on 2021-02-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[(1, 'Patient'), (2, 'Donor')], default=1, max_length=15),
        ),
    ]
