# Generated by Django 3.1.6 on 2021-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Donor', 'Donor')], default='Patient', max_length=15),
        ),
    ]
