# Generated by Django 3.1.6 on 2021-02-16 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_auto_20210216_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='appointment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
